name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm test
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - run: npm run prepare
    - uses: ./
      with:
        openai_api_key: ${{ secrets.OPENAI_API_KEY }}
